#!/usr/bin/env python

import argparse
import toml
from patter import Trainer


def get_parser():
    parser = argparse.ArgumentParser(description="Patter STT Trainer")
    parser.add_argument("--corpus-config", required=True, help="Configuration file specifying corpus")
    parser.add_argument("--model-config", required=True, help="Configuration file specifying model settings")
    parser.add_argument("--training-config", required=True, help="Configuration file specifying training parameters")

    return parser


def main():
    args = get_parser().parse_args()

    # load configurations
    with open(args.corpus_config, "r") as fh:
        corpus_config = toml.load(fh)
    with open(args.model_config, "r") as fh:
        model_config = toml.load(fh)
    with open(args.training_config, "r") as fh:
        training_config = toml.load(fh)

    Trainer.load(training_config).train(model_config, corpus_config)


if __name__ == '__main__':
    main()
