#!/usr/bin/env python

import argparse
import toml
from patter import ModelFactory
from patter.data import AudioDataset


def get_parser():
    parser = argparse.ArgumentParser(description="Patter STT Test")
    parser.add_argument("model_path", help="Begin training with this model")

    return parser


def main():
    args = get_parser().parse_args()

    # load the model
    model = ModelFactory.load(args.model_path)

    # print model structure and metadata
    print(model)
    print(model.config)


if __name__ == '__main__':
    main()
