#!/usr/bin/env python

import argparse
import toml
from patter import Evaluator, ModelFactory
from patter.data import AudioDataset


def get_parser():
    parser = argparse.ArgumentParser(description="Patter STT Test")
    parser.add_argument("--corpus-config", required=True, help="Configuration file specifying corpus")
    parser.add_argument("--test-config", required=True, help="Configuration file specifying testing parameters")
    parser.add_argument("--progress", action="store_true", help="If true, display progress bars, else use text output")
    parser.add_argument("--model-path", required=True, help="Begin training with this model")

    return parser


def main():
    args = get_parser().parse_args()

    # load configurations
    with open(args.corpus_config, "r") as fh:
        corpus_config = toml.load(fh)
    with open(args.testing_config, "r") as fh:
        testing_config = toml.load(fh)

    # initialize the model to test
    model = ModelFactory.load(args.model_path)

    # set up trainer and corpus
    eval = Evaluator.load(testing_config, tqdm=args.progress)

    # load the corpora
    test_corpus = AudioDataset.from_config(corpus_config, model.input_cfg, model.labels, manifest="test")

    # kick off the test
    eval.eval(model, test_corpus)

if __name__ == '__main__':
    main()
