#!/usr/bin/env python

import argparse
from patter import ModelFactory
from patter.models import


def get_parser():
    parser = argparse.ArgumentParser(description="Patter STT Model Inspection")
    parser.add_argument("--model-path", required=False, help="Begin training with this model")

    return parser


def main():
    args = get_parser().parse_args()
    model = ModelFactory.load(args.model_checkpoint)

    print(model.config)


if __name__ == '__main__':
    main()
